#!/usr/bin/env bash
# infra/setup-mariadb-replica.sh
#
# Sets up a second MariaDB 10.4 instance (Replica) on Ubuntu 24.04 (Azure VM).
# The Replica runs as a separate process on port 3307 with its own datadir
# (/var/lib/mysql-replica) and a dedicated systemd service (mariadb-replica).
#
# Requirements: 5.2, 5.3
#
# Usage:
#   sudo bash infra/setup-mariadb-replica.sh
#
# This script is idempotent: each step is skipped if already done.
# Run setup-mariadb-primary.sh first, then this script, then
# infra/setup-mariadb-replication.sh (task 2.2) to wire the replication.

set -euo pipefail

# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------

log()  { echo "[INFO]  $*"; }
err()  { echo "[ERROR] $*" >&2; exit 1; }
warn() { echo "[WARN]  $*"; }

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------

if [[ "$(id -u)" -ne 0 ]]; then
    err "This script must be run as root (use: sudo bash $0)"
fi

# mariadb-server must already be installed by setup-mariadb-primary.sh
if ! dpkg -s mariadb-server &>/dev/null; then
    err "mariadb-server is not installed. Run infra/setup-mariadb-primary.sh first."
fi

log "=== MariaDB Replica setup started ==="

# ---------------------------------------------------------------------------
# Configuration constants
# ---------------------------------------------------------------------------

REPLICA_DATADIR="/var/lib/mysql-replica"
REPLICA_CNF_DIR="/etc/mysql/replica"
REPLICA_CNF="${REPLICA_CNF_DIR}/my.cnf"
REPLICA_PORT="3307"
REPLICA_SOCKET="/var/run/mysqld/mysqld-replica.sock"
REPLICA_PID="/var/run/mysqld/mysqld-replica.pid"
REPLICA_LOG="/var/log/mysql/error-replica.log"
REPLICA_SERVICE="mariadb-replica"

# ---------------------------------------------------------------------------
# Step 1: Create replica datadir
# ---------------------------------------------------------------------------

if [[ -d "${REPLICA_DATADIR}" ]]; then
    log "Datadir ${REPLICA_DATADIR} already exists — skipping creation"
else
    log "Creating datadir ${REPLICA_DATADIR}..."
    mkdir -p "${REPLICA_DATADIR}"
    chown mysql:mysql "${REPLICA_DATADIR}"
    chmod 750 "${REPLICA_DATADIR}"
    log "Datadir created: ${REPLICA_DATADIR}"
fi

# Ensure the mysql user owns the directory (idempotent)
chown mysql:mysql "${REPLICA_DATADIR}"

# ---------------------------------------------------------------------------
# Step 2: Write /etc/mysql/replica/my.cnf
# ---------------------------------------------------------------------------

if [[ -f "${REPLICA_CNF}" ]]; then
    log "${REPLICA_CNF} already exists — skipping write"
else
    log "Writing ${REPLICA_CNF}..."
    mkdir -p "${REPLICA_CNF_DIR}"

    cat > "${REPLICA_CNF}" <<EOF
# MariaDB Replica configuration — generated by setup-mariadb-replica.sh
[mysqld]
server-id       = 2
read_only       = 1
port            = ${REPLICA_PORT}
socket          = ${REPLICA_SOCKET}
pid-file        = ${REPLICA_PID}
datadir         = ${REPLICA_DATADIR}
log_error       = ${REPLICA_LOG}
relay-log       = relay-bin
bind-address    = 127.0.0.1
EOF

    log "Configuration written to ${REPLICA_CNF}"
fi

# ---------------------------------------------------------------------------
# Step 3: Initialize the replica datadir
# ---------------------------------------------------------------------------

# mysql_install_db creates subdirectories like 'mysql/' inside the datadir.
# If the 'mysql' system schema already exists the datadir is already initialized.
if [[ -d "${REPLICA_DATADIR}/mysql" ]]; then
    log "Datadir already initialized (${REPLICA_DATADIR}/mysql exists) — skipping mysql_install_db"
else
    log "Initializing replica datadir with mysql_install_db..."
    mysql_install_db \
        --defaults-file="${REPLICA_CNF}" \
        --user=mysql \
        || err "mysql_install_db failed — check ${REPLICA_LOG} for details"
    log "Datadir initialized successfully"
fi

# ---------------------------------------------------------------------------
# Step 4: Create and enable the mariadb-replica systemd service
# ---------------------------------------------------------------------------

SERVICE_FILE="/etc/systemd/system/${REPLICA_SERVICE}.service"

if [[ -f "${SERVICE_FILE}" ]]; then
    log "Systemd service file ${SERVICE_FILE} already exists — skipping creation"
else
    log "Creating systemd service ${REPLICA_SERVICE}..."

    cat > "${SERVICE_FILE}" <<EOF
[Unit]
Description=MariaDB 10.4 Replica (port ${REPLICA_PORT})
Documentation=man:mysqld(8)
After=network.target mariadb.service
Wants=mariadb.service

[Service]
Type=simple
User=mysql
Group=mysql
ExecStart=/usr/sbin/mysqld --defaults-file=${REPLICA_CNF} --user=mysql
ExecStop=/usr/bin/mysqladmin --defaults-file=${REPLICA_CNF} --socket=${REPLICA_SOCKET} shutdown
TimeoutStartSec=60
TimeoutStopSec=60
# Restart on failure, but not if manually stopped
Restart=on-failure
RestartSec=5s
# Ensure the run directory exists before starting
ExecStartPre=/bin/mkdir -p /var/run/mysqld
ExecStartPre=/bin/chown mysql:mysql /var/run/mysqld

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    log "Systemd service ${REPLICA_SERVICE} created"
fi

# Enable the service so it starts on boot (idempotent)
systemctl enable "${REPLICA_SERVICE}" --quiet
log "Service ${REPLICA_SERVICE} enabled"

# ---------------------------------------------------------------------------
# Step 5: Start the service (if not already running)
# ---------------------------------------------------------------------------

if systemctl is-active --quiet "${REPLICA_SERVICE}"; then
    log "Service ${REPLICA_SERVICE} is already running — skipping start"
else
    log "Starting ${REPLICA_SERVICE}..."
    systemctl start "${REPLICA_SERVICE}" \
        || err "Failed to start ${REPLICA_SERVICE} — check: journalctl -u ${REPLICA_SERVICE} -n 50"
    log "Service ${REPLICA_SERVICE} started"
fi

# ---------------------------------------------------------------------------
# Step 6: Verify the replica is listening on 127.0.0.1:3307
# ---------------------------------------------------------------------------

log "Verifying replica is listening on 127.0.0.1:${REPLICA_PORT}..."

# Give the process up to 15 seconds to open the port
WAIT_SECS=15
for i in $(seq 1 "${WAIT_SECS}"); do
    if ss -tlnp | grep -q "127.0.0.1:${REPLICA_PORT}"; then
        log "Replica is listening on 127.0.0.1:${REPLICA_PORT} (confirmed after ${i}s)"
        break
    fi
    if [[ "${i}" -eq "${WAIT_SECS}" ]]; then
        err "Replica did not start listening on 127.0.0.1:${REPLICA_PORT} within ${WAIT_SECS}s — check: journalctl -u ${REPLICA_SERVICE} -n 50"
    fi
    sleep 1
done

# Secondary check: verify via socket ping
if mysqladmin --socket="${REPLICA_SOCKET}" ping --connect-timeout=5 &>/dev/null; then
    log "mysqladmin ping on ${REPLICA_SOCKET}: OK"
else
    warn "mysqladmin ping on socket did not respond — port is open but socket may not be ready yet"
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

log ""
log "=== MariaDB Replica setup completed successfully ==="
log "  Datadir        : ${REPLICA_DATADIR}"
log "  Config file    : ${REPLICA_CNF}"
log "  Port           : ${REPLICA_PORT} (bind: 127.0.0.1)"
log "  Socket         : ${REPLICA_SOCKET}"
log "  Log            : ${REPLICA_LOG}"
log "  Systemd service: ${REPLICA_SERVICE} (enabled, running)"
log ""
log "Next step: configure Primary → Replica replication with infra/setup-mariadb-replication.sh (task 2.2)"
